export const AI_MODEL_OPTIONS = [
  'AI_MODEL_GPT_4O',
  'AI_MODEL_GPT_4O_MINI',
  'AI_MODEL_GPT_4',
  'AI_MODEL_GPT_3_5_TURBO',
  'AI_MODEL_GPT_5',
  'AI_MODEL_GPT_5_MINI',
  'AI_MODEL_GPT_5_CHAT',
  'AI_MODEL_UNSPECIFIED',
] as const;
